name: Build packages

on: [push]

jobs:
  determine_feed:
    name: Determine feeds
    runs-on: ubuntu-latest
    outputs:
      feed: ${{ steps.set-matrix.outputs.feed }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set matrix
      id: set-matrix
      run: |
        FEEDS="$(ls -d */ | cut -f1 -d'/')"

        JSON='{"feed":['
        FIRST=1
        for FEED in $FEEDS; do
          [[ $FIRST -ne 1 ]] && JSON="$JSON"','
          JSON="$JSON"'"'"${FEED}"'"'
          FIRST=0
        done
        JSON="$JSON"']}'

        echo -e "\n---- feeds ----\n"
        echo "$JSON"
        echo -e "\n---- feeds ----\n"
        echo "::set-output name=feed::$JSON"


  build:
    runs-on: ubuntu-latest
    needs: determine_feed
    strategy:
      matrix: ${{fromJson(needs.determine_feed.outputs.feed)}}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: True

      - name: Build
        uses: aparcar/action-openwrt-sdk@make_single
        env:
          FEEDNAME: ${{ matrix.feed }}
          FEEDPATH: ${{ matrix.feed }}

      - name: Upload
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: package-builder
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_ENDPOINT: https://images.aparcar.org
          SOURCE_DIR: bin/packages/x86_64/${{ matrix.feedname }}
          DEST_DIR: packages/

